### ISSUE TITLE
Programming the 'del' key for a hold key function

### ISSUE THREAD

**Issue by Bow3ryList** [shaoxiongduan/calculator#9]
Hi Shao,

Is it possible to program the 'del' key on the macropad so that when the key is held it starts repeatedly pressing the key, similar to how the backpack key works on a keyboard?

Just wondering if there is an easy way to implement it?

Thanks

Tom

**Comment by yangnuozhen** [comment]
I added this between https://github.com/shaoxiongduan/sci-calc/blob/8db8b3062902c7a97a66d7f8695507e86526fe55/sci_calc_code/src/UIElements/InputBox.cpp#L180-L181:

```cpp
if (kb.getRisingEdgeKey() == std::make_pair(4, 3)){
        int curtime = millis();
        bool repeatDelete = false;
        int lastDeleteTime = curtime;
        while (kb.getKey(4, 3).getIsPressed()) {
            delay(20);
            if (millis() - curtime > 1000){
                repeatDelete = true;
            }
            if (repeatDelete && (millis() - lastDeleteTime > 100)){
                Serial.println("deleting str[Repeat]");
                deleteStr();
                u8g2.clearBuffer();
                draw();
                u8g2.sendBuffer();
                lastDeleteTime = millis();
            }
            kb.update();
        }
    }
```

https://github.com/user-attachments/assets/4e8e056a-10e1-43e7-b67c-b17b7dfaf8a6


However, the above code does not fully meet the expected effect. Since the while loop blocks the main loop `loop()`, we have to clear and resend the buffer of u8g2. This results in only the InputBox element being drawn correctly, while other elements disappear.

But I can't think of a better solution at the moment. Theoretically, the update() process and loop() loop should not be blocked, so this solution is very likely not feasible...

**Comment by Bow3ryList** [comment]
Nice, that worked for me on the calculator.

I wonder if it is possible to do something similar for the macro pad?
